### ISSUE TITLE
Interesting, any idea to develop this further

### ISSUE THREAD

**Issue by sjaakd** [bjornharrtell/ogc-tools#1]
@bjornharrtell : I reckon this is an evolution of the work done in highsource of JtsToGml311. I've made similar adaptations to the same library to make it suited for Gml321 (at my job). Any ideas to take this a step further?

**Comment by bjornharrtell** [comment]
Sorry no, not at the moment... in the end (two years ago) I opted for a more brute force solution to convert the GML and since then I have not had any cases where I need the compatibility any longer.

**Comment by sjaakd** [comment]
Ok.. Thanks!
